### ISSUE TITLE
Expression environment

### ISSUE THREAD

**Issue by JohnCoene** [blockr-org/blockr#64]
Would it be possible to further simplify the expression to remove the `.(var)`, I know it's not complicated but the audience may be confused.

I know we can load an environment in a function with the replacement function `environment<-`, if we could do something like this may be we could get rid of `.(var)`?

**Comment by DivadNojnarg** [comment]
Did you show the code to the audience or this appeared in the application code outputs?

**Comment by JohnCoene** [comment]
Yes I created [this](https://github.com/blockr-org/blockr/blob/main/R/create.R) ran it + with a hack on `block.demo` had it appear in the UI and worked with drag and drop

**Comment by nbenn** [comment]
@JohnCoene I'm happy to have a discussion on this, but you might have to be slightly more specific for me to understand what it is that you want to achieve.

Some thoughts:

- In an early version, I was using `substitute()` instead of `bquote()` to plug in values into our quoted expressions. It allows for more concise but less explicit substitution.

    ```r
    env <- list2env(list(letters = letters[1:3], letter = "d"))
    eval(substitute(letter %in% letters, env))
    #> [1] FALSE
    eval(bquote(.(letter) %in% letters, env))
    #> [1] TRUE
    ```

- I also played with specifying block-level expressions as functions. What I did not like about that approach is that (for substitution/code generation) you have to take into account the function environment (the environment the function was defined in), together with all its parents and the environment holding data and values. This makes for a more complicated setup where it is a lot less clear where things are coming from that are used for substitution. You also have the problem above, that you don't have available the user's intention when doing the substitution and have to substitute every symbol than can be looked up in any of there environments.

**Comment by JohnCoene** [comment]
Sorry, I did not phrase that well.

I essentially meant to use `substitute` over `bquote` because it simplifies the expression block developers have to write, from `.(x) + 1` to `x + 1`

I did not know you had used `substitute` in a previous version, if you think `bquote` is better it's totally fine by me, we can close this.
