### ISSUE TITLE
Magrittr

### ISSUE THREAD

**Issue by JohnCoene** [blockr-org/blockr#81]
Is there a reason we rely on magrittr instead of the native pipe?

https://github.com/blockr-org/blockr/blob/9c88b24a7597ff86af5b69714f25952778d391da/R/block.R#L128

**Comment by nbenn** [comment]
The reason is that the base pipe is implemented as a "syntax transformation" and not as an operator (i.e. function) as is the case with ``magrittr::`%>%`()``. With the magrittr pipe we can do

```r
ex1 <- quote(iris)
ex2 <- quote(dplyr::filter(Species == "setosa" & Sepal.Width > 4))

substitute(x %>% y, list(x = ex1, y = ex2))
#> iris %>% filter(Species == "setosa" & Sepal.Width > 4)
```

and with the base pipe we cannot

```r
substitute(x |> y, list(x = ex1, y = ex2))
#> Error: The pipe operator requires a function call as RHS
```

We can make this work with the base pipe for example as

```r
ex1 <- quote(iris)
ex2 <- quote(\(x) dplyr::filter(x, Species == "setosa" & Sepal.Width > 4))

substitute(x |> y(), list(x = ex1, y = ex2))
#> (function(x) dplyr::filter(x, Species == "setosa" & Sepal.Width > 4))(iris)
```

but the resulting expression is harder to read (for a human). There might be ways around this problem (using the base pipe; not sure though), but at the time I just felt it was easier to simply go with the magrittr pipe.

cc @christophsax as "clean generated code" was one of your core requirements.

**Comment by christophsax** [comment]
Will be revisited at a later point
